# Generated by Django 4.1.7 on 2023-02-19 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter route name', max_length=20)),
                ('grade', models.CharField(choices=[('V0', 'V0'), ('V1', 'V1'), ('V2', 'V2'), ('V3', 'V3'), ('V4', 'V4'), ('V5', 'V5'), ('V6', 'V6'), ('V7', 'V7'), ('V8', 'V8'), ('V9', 'V9'), ('V10', 'V10'), ('V11', 'V11'), ('V12', 'V12')], default='V0', max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter wall name', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='./images')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WallHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walls.wall')),
            ],
        ),
        migrations.CreateModel(
            name='RouteHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_type', models.CharField(choices=[('Foot', 'Foot'), ('Start', 'Start'), ('Hold', 'Hold'), ('Finish', 'Finish')], default='Hold', max_length=6)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walls.route')),
                ('wall_hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walls.wallhold')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='wall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walls.wall'),
        ),
    ]
