# Generated by Django 4.1.7 on 2023-02-19 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='wall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='walls.wall'),
        ),
        migrations.AlterField(
            model_name='routehold',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='walls.route'),
        ),
        migrations.AlterField(
            model_name='routehold',
            name='wall_hold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_holds', to='walls.wallhold'),
        ),
        migrations.AlterField(
            model_name='wallhold',
            name='wall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walls', to='walls.wall'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('wall', 'name')},
        ),
    ]
